### ISSUE TITLE
 can`t upgrade pip to the newest version 9.0.1 (OS:ubuntu 16.04LTS)

### ISSUE THREAD

**Issue by lwj7790** [lwj7790/TF-practice#2]
~$ sudo -H pip install jupyter
Collecting jupyter
  Using cached jupyter-1.0.0-py2.py3-none-any.whl
Collecting ipykernel (from jupyter)
  Using cached ipykernel-4.6.1-py2-none-any.whl
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-5.1.0-py2.py3-none-any.whl
Collecting qtconsole (from jupyter)
  Using cached qtconsole-4.3.0-py2.py3-none-any.whl
Collecting notebook (from jupyter)
  Using cached notebook-5.0.0-py2.py3-none-any.whl
Collecting ipywidgets (from jupyter)
  Using cached ipywidgets-6.0.0-py2.py3-none-any.whl
Collecting nbconvert (from jupyter)
  Using cached nbconvert-5.1.1-py2.py3-none-any.whl
Collecting ipython>=4.0.0 (from ipykernel->jupyter)
  Using cached ipython-6.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Beginning with IPython 6.0, Python 3.3 and above is required.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0) detected.
    Your pip version is out of date, please install pip >= 9.0.1. pip 8.1.1 detected.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-No8Nw7/ipython/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by lwj7790** [comment]
https://github.com/ipython/ipython/blob/master/README.rst

**Comment by ys7yoo** [comment]
First, you should upgrade pip itself.
Run 
`pip install --upgrade pip`

Next, check the python version by typing 
`python --version`
You may need to upgrade python itself.

To update Python see the following link: [https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get)

Basically, you can do
```
sudo apt-get update
sudo apt-get install python3.6
``` 

Hope this helps.
