### ISSUE TITLE
tensorflow import error in jupyter 

### ISSUE THREAD

**Issue by lwj7790** [lwj7790/TF-practice#6]
I installed tensorflow in my laptop.
When I tested on desktop, it works well in both terminal and jupyter
But in my laptop, tensorflow doesn't import in jupyter notebook.
I want to know reason why it doesn't work and how to solve it

**Comment by lwj7790** [comment]
wonjin@jin:~$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> exit()


//works well


ipython notebook


import tensorflow as tf

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

ImportError: No module named 'tensorflow'

**Comment by ys7yoo** [comment]
How did you install tensor flow?

I recommend to use pip with --user flag, which does not mess up with the system settings. 

pip3 install tensorflow --user
